#!/bin/bash

set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Installing dotfiles from $DOTFILES_DIR..."

symlink() {
  local src="$1"
  local dest="$2"

  mkdir -p "$(dirname "$dest")"

  if [ -L "$dest" ]; then
    echo "  updating symlink: $dest"
    ln -sf "$src" "$dest"
  elif [ -f "$dest" ]; then
    echo "  backing up existing file: $dest -> $dest.bak"
    mv "$dest" "$dest.bak"
    ln -sf "$src" "$dest"
  else
    echo "  linking: $dest"
    ln -sf "$src" "$dest"
  fi
}

# Bash
symlink "$DOTFILES_DIR/bash/.bashrc" "$HOME/.bashrc"

# Neovim
symlink "$DOTFILES_DIR/nvim/init.lua" "$HOME/.config/nvim/init.lua"

# Tmux
symlink "$DOTFILES_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"

# WezTerm (Windows app — can't follow WSL symlinks, so write a stub that loads
# the real config live from the WSL repo over the \\wsl.localhost UNC path.
# This makes edits hot-reload; no re-copy needed after changing the config.)
WINDOWS_HOME="/mnt/c/Users/$(cmd.exe /c 'echo %USERNAME%' 2>/dev/null | tr -d '\r')"
WSL_CONFIG="\\\\wsl.localhost\\${WSL_DISTRO_NAME}\\home\\${USER}\\dotfiles\\wezterm\\.wezterm.lua"

echo "  writing wezterm stub: $WINDOWS_HOME/.wezterm.lua"
cat > "$WINDOWS_HOME/.wezterm.lua" <<EOF
-- Auto-generated by dotfiles/install.sh — do NOT edit here.
-- Loads the real config live from the WSL dotfiles repo and watches it for changes,
-- so edits in ~/dotfiles/wezterm/.wezterm.lua hot-reload automatically.
local wezterm = require 'wezterm'
local wsl_config = [[${WSL_CONFIG}]]
wezterm.add_to_config_reload_watch_list(wsl_config)
return dofile(wsl_config)
EOF

echo ""
echo "Done. Reload your shell with: source ~/.bashrc"
