-- ============================================================================
--  motions.lua — get around as fast as possible
-- ============================================================================
--
--  Open in nvim:   nvim nvim/motions.lua
--
--  This is a hands-on drill file for MOVING, not editing. Every section has a
--  `TRY IT` with a real target in this buffer. Do them in normal mode (press
--  `jk` or <Esc> first). Stay off the arrow keys — the whole point is to reach
--  for these instead.
--
--  The golden rule: NEVER press `hjkl` more than a couple times in a row. If a
--  target is far, there's a faster motion below to get there in one jump.
--
--  TIP: counted jumps like `5j` are aimed by READING the gutter, never by
--  counting rows. init.lua sets hybrid line numbers (number + relativenumber),
--  so the cursor line shows its absolute number and every other line shows how
--  far away it is — the number you type.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  1. WITHIN A LINE  — stop walking with `l`
-- ----------------------------------------------------------------------------
--    w / W   forward to start of next word  (W = ignore punctuation)
--    b / B   back to start of previous word
--    e / ge  end of word (forward / backward)
--    0       first column      ^   first non-blank      $   end of line
--    f{c}    jump forward ONTO the next {c} on this line
--    t{c}    jump forward UP TO (just before) the next {c}
--    F / T   same, backwards            ;  repeat last f/t      ,  reverse it
--    %       jump to the matching ) ] }
--
--  TRY IT on the line below (put cursor at its start with `0`):
--    * press `w` a few times to hop word-to-word
--    * press `$` to shoot to the end, `^` to come back to the first word
--    * press `f(` to land on the paren, then `%` to bounce to its match
--    * press `t,` to stop right before the comma, then `;` for the next one
local sample = "choose(alpha, beta, gamma, delta)"   -- targets: ( ) , , words


-- ----------------------------------------------------------------------------
--  2. FIND-CHAR IS YOUR FASTEST HORIZONTAL MOVE
-- ----------------------------------------------------------------------------
--  `f` / `t` beat mashing `w`. Think "I want to be AT the x" -> `fx`.
--  Overshot? `,` steps back. Wrong char? just `f{other}`.
--
--  TRY IT: from column 0 of the line below, reach the word "needle" in ONE
--  press with `fn` (then `;` if it lands on the wrong n). Then `$` and `Fh`
--  to fly back to the "h" in "haystack".
--    haystack haystack haystack needle haystack haystack


-- ----------------------------------------------------------------------------
--  3. UP AND DOWN THE FILE
-- ----------------------------------------------------------------------------
--    gg      top of file            G       bottom of file
--    {count}G / :{count}   go to an absolute line number  (e.g. 120G)
--    {count}j / {count}k   jump N lines (5j = down 5) — pair with relativenumber
--    {  }    previous / next blank-line paragraph  (great for code blocks)
--    Ctrl-d  half page down         Ctrl-u  half page up   (keeps context)
--    M-d     same as Ctrl-d          M-u     same as Ctrl-u
--            -- M-u/M-d also scroll tmux copy mode and the claude TUI, so
--            one pair of keys scrolls every pane whatever is running in it
--    Ctrl-f  full page forward      Ctrl-b  full page back
--    H M L   jump to the top / middle / bottom of the VISIBLE screen
--    zz zt zb  scroll current line to center / top / bottom (reframe, don't move)
--
--  TRY IT:
--    * press `G` to hit the bottom of the file, then `gg` to snap back here
--    * press `}` a few times to skip paragraph-by-paragraph through this file
--    * press `L` to drop to the bottom of the screen, `H` for the top, `M` mid
--    * press `Ctrl-d`, then `zz` to recenter what you land on


-- ----------------------------------------------------------------------------
--  3b. FLASH — jump to anywhere you can SEE, by naming it
-- ----------------------------------------------------------------------------
--  `s` then the first two characters of the target. Every match on screen gets
--  a label; press the label and you are there. Works forwards and backwards,
--  across the whole window, in one motion.
--
--  This covers the range f/t cannot (not on this line) and `/` handles clumsily
--  (you have to make the pattern unique, then n-n-n to the right hit). If you
--  are ever holding j or k to reach something you can already see, this is the
--  key you wanted.
--
--  It is also an OPERATOR target: `ds{ch}{ch}` deletes from here to the label,
--  `ys..` yanks to it, and in visual mode `s..` extends the selection there.
--
--  TRY IT: from the top of this file, `s` then `de` and jump to a `delta` far
--  below. Then `d` `s` and a label to delete everything between.
--
--  `s` shadows the built-in substitute-character; `cl` does the same job.
--  Inside neo-tree, `s` still opens a vsplit — its mapping is buffer-local.

-- ----------------------------------------------------------------------------
--  4. SEARCH — teleport to anything by name
-- ----------------------------------------------------------------------------
--    /text<CR>   search forward       ?text<CR>   search backward
--    n / N       next / previous match (N = opposite direction)
--    *  / #      search for the WORD under the cursor, forward / back
--    (with hlsearch, `:noh` clears the highlight when you're done)
--
--  Searching is usually the FASTEST way to cross a file — if you can see it or
--  name it, `/` gets you there without counting a single line.
--
--  TRY IT: put the cursor on the word `waypoint` below and press `*` — you'll
--  jump straight to its next occurrence; keep pressing `n` to cycle them.
local waypoint = 1
-- ... some distance later ...
local reuse_the_waypoint = waypoint + waypoint   -- * from above lands here


-- ----------------------------------------------------------------------------
--  5. MARKS & THE JUMP LIST — leave, then come back
-- ----------------------------------------------------------------------------
--    m{a-z}   drop a named mark here      `{a-z}   jump back to that mark
--    ``       jump back to where you were BEFORE the last big jump
--    Ctrl-o   go back through your jump history (older positions)
--    Ctrl-i   go forward again (Tab)      :jumps   see the whole list
--    gd / gr  (this config, LSP) jump to a symbol's definition / references
--    ]d / [d  (this config, LSP) jump to the next / previous diagnostic
--    K        (this config, LSP) peek hover docs without leaving your spot
--
--  This is how you bounce between two spots without pinning them in harpoon.
--
--  TRY IT: press `ma` here to set mark 'a'. Now `G` to the bottom, poke
--  around, then press `` `a `` to teleport back to this exact line. Try `Ctrl-o`
--  / `Ctrl-i` to walk your jump history.


-- ----------------------------------------------------------------------------
--  6. MOTIONS + OPERATORS = editing at the same speed
-- ----------------------------------------------------------------------------
--  Every motion above doubles as a target for an operator. Same keys, now they
--  DO something over the distance they'd move:
--    d{motion}  delete   c{motion}  change   y{motion}  yank
--    dw  d$  d^        ci(  "change inside ()"      di"  yi{
--    daw "delete a word"    dt,  "delete up to the comma"    d/foo  to a search
--    ciw is the workhorse: change the whole word the cursor is on, anywhere in it
--
--  TRY IT: put the cursor anywhere inside the parens below and press `ci(` —
--  the args vanish and you're in insert mode ready to retype. Or `diw` on a
--  word to nuke just that word.
local edit_me = "build(one, two, three)"


-- ----------------------------------------------------------------------------
--  7. PROJECT-WIDE — when the target isn't in this file (this config)
-- ----------------------------------------------------------------------------
--  Once you're fast within a file, jumping BETWEEN files is the next win.
--  Rule of thumb: within a file use `/` and `f`; across files use telescope;
--  for the 2-4 files you live in, pin them with harpoon.
--
--  TELESCOPE  (nvim-telescope/telescope.nvim, powered by plenary.nvim)
--    <leader>ff   find files by name
--    <leader>fg   live grep — search file *contents* across the project
--    <leader>fb   jump between open buffers
--    <leader>fh   search neovim's :help docs
--    <leader>fe   file browser, opened at the current file's directory
--                 (telescope-file-browser.nvim; also creates/renames/deletes)
--
--    telescope-ui-select.nvim also routes vim.ui.select() here, so every menu
--    nvim raises is a telescope dropdown you can fuzzy-filter rather than a
--    numbered list you read: <leader>ca code actions, <leader>mm / <leader>dM
--    make targets. Type to narrow, <CR> to pick, <Esc> to back out.
--
--  NEO-TREE  (nvim-neo-tree/neo-tree.nvim) — the sidebar tree, for browsing
--  structure rather than jumping to a file you can already name.
--    <leader>e    toggle the sidebar, revealing the current file in the tree
--    <space>      expand / collapse the directory under the cursor, in place
--    <CR>         open — a file in the last window, a directory expands it
--    C  /  z      collapse this node / collapse every node
--    <bs>         move the tree root up one directory
--    .            make the directory under the cursor the new root
--    s  /  S  /  t  open in a vsplit / split / new tab
--    P            floating preview without leaving the tree (<C-f>/<C-b> scroll)
--    a  A  d  r   add file / add directory / delete / rename
--    y  x  p      copy / cut / paste under the cursor
--    H            toggle hidden + gitignored files
--    /  f         fuzzy-find within the tree / filter and keep the filter
--    [g  ]g       previous / next git-modified file
--    <  >         switch source: filesystem / buffers / git status
--    ?            full keymap help, inside the tree
--
--  HARPOON  (ThePrimeagen/harpoon, branch harpoon2)
--    <leader>a    pin the current file to the list
--    <leader>h    toggle the quick menu (reorder / remove pins)
--    <leader>1    teleport to pinned file 1
--    <leader>2    teleport to pinned file 2
--    <leader>3    teleport to pinned file 3
--    <leader>4    teleport to pinned file 4


-- ----------------------------------------------------------------------------
--  8. THE REST OF YOUR KEYMAPS — every custom binding in init.lua
-- ----------------------------------------------------------------------------
--  Not strictly "motions", but this is the full set so nothing's a surprise.
--
--  LSP  (neovim/nvim-lspconfig; servers installed by mason.nvim +
--        mason-lspconfig.nvim — lua_ls is auto-installed)
--    gd           go to definition        (opens a telescope picker)
--    gr           find references         (opens a telescope picker)
--    K            hover docs
--    ]d / [d      next / previous diagnostic
--    <leader>rn   rename the symbol everywhere
--    <leader>ca   code actions (quick fixes)
--
--  COMPLETION  (hrsh7th/nvim-cmp + sources cmp-nvim-lsp, cmp-buffer, cmp-path;
--               snippets via L3MON4D3/LuaSnip + saadparwaiz1/cmp_luasnip)
--    <C-Space>    force the completion menu open
--    <Tab> / <S-Tab>   next / prev item (and hop between snippet fields)
--    <CR>         confirm the highlighted item
--    <C-f> / <C-b>     scroll the docs popup down / up
--
--  DEBUGGER  (mfussenegger/nvim-dap + rcarriga/nvim-dap-ui; the debugpy
--             adapter is installed by jay-babu/mason-nvim-dap.nvim, and the
--             python configurations come from mfussenegger/nvim-dap-python)
--
--  Same protocol and same adapter VS Code uses, so behaviour is identical --
--  what dap-ui adds is the windows. Two ways in:
--    <F5>         pick a configuration. In a project with .vscode/launch.json,
--                 that file's configurations are in the list automatically --
--                 nvim-dap reads it on demand, so VS Code's Run-and-Debug
--                 dropdown and this picker are literally the same list.
--    <leader>dM   pick a Makefile target instead (see Running, below).
--  Either way, put the cursor on a line and <leader>db first.
--
--  launch.json caveat: nvim's JSON parser is stricter than VS Code's. Trailing
--  commas, and `//` comments sharing a line with code, make the whole file
--  unparseable and nvim-dap silently falls back to the generic configs. Put
--  comments on their own line and drop the trailing commas.
--
--    hjkl, with the call stack drawn vertically — callees below, callers above,
--    and execution running left to right along the current line:
--      <leader>dl   step OVER — carry on rightwards; calls run, you don't descend
--      <leader>dj   step INTO — drop DOWN into the callee
--      <leader>dk   step OUT  — come back UP to the caller
--      <leader>dK   look UP one frame    — same directions, nothing executed:
--      <leader>dJ   look DOWN one frame    only the frame you're inspecting
--                   changes. So dk and dK both reach the caller — dk by running
--                   the rest of the function, dK by only looking. Scopes and
--                   <leader>de follow the selected frame.
--
--    The same three moves on ONE key, and from ANY window -- the dap-ui panes
--    included, so a step you think of while reading the scopes pane doesn't
--    cost a trip back to the code first:
--      <C-l>        step OVER      <C-j>   step INTO      <C-k>   step OUT
--    Nothing is shadowed: with no session stopped each key does what it always
--    did, so <C-l> still redraws and clears the search highlight.
--
--    F-keys, exactly VS Code's:
--      <F5>       start a session / resume from a stop
--      <F10>      step over          <F11>   step into
--      <S-F11>    step out           <F12>   step out (fallback binding)
--
--    Breakpoints:
--      <leader>db   toggle a breakpoint on this line
--      <leader>dB   conditional -- prompts for a python expression (`i == 4721`)
--      <leader>dp   logpoint -- prints to the repl and never stops; `{}`
--                   interpolates, so `row {i} = {row}`. A print statement that
--                   isn't in the file and can't be committed by accident.
--      <leader>dx   clear every breakpoint
--
--    Running:
--      <leader>mm   pick a Makefile target and just RUN it in a terminal split
--                   -- no debugger, no attach. The everyday case; <leader>dM is
--                   the same picker when you want to stop inside it.
--      <leader>dM   pick a Makefile target, run it with DEBUG=1 in a terminal
--                   split, and attach automatically -- the whole IDE "Run"
--                   button, but parameterised by the Makefile rather than by a
--                   second copy of the arguments. Prompts for extra make vars
--                   (`BOOTSTRAPS=5 CONFIDENCE=0.8`). Set breakpoints FIRST:
--                   --wait-for-client releases the moment nvim attaches.
--      <leader>dc   continue (same as <F5>)
--      <leader>dC   run to the cursor -- one-shot breakpoint here, then resume
--      <leader>dR   re-run the last configuration, skipping the picker
--      <leader>dm   debug the test method the cursor is inside (pytest/unittest)
--      <leader>dt   terminate the session -- a HARD kill of the process, not a
--                   Ctrl-C, so no KeyboardInterrupt and no `finally` blocks. To
--                   let a run wind down cleanly, Ctrl-C its terminal split
--                   instead; to stop debugging but let it finish, use
--                   :lua require('dap').disconnect({terminateDebuggee = false})
--      <leader>dq   tidy up: terminate if still running, then close the panes,
--                   the repl, and the <leader>dM terminal split. The dap-ui
--                   panes close on their own when a session ends -- this is for
--                   the terminal split, which is kept on purpose so the run's
--                   output outlives the session. Also as :DebugCleanup, and it
--                   reports how many splits it closed rather than failing quiet.
--
--    When it breaks:
--      <leader>dE   cycle what stops the program: uncaught -> raised+uncaught
--                   -> none. `uncaught` is on by default (dap.defaults.python),
--                   so a traceback HALTS on the throwing line with the frame
--                   still live instead of ending the session and leaving you to
--                   read a traceback with no locals behind it. `raised` stops on
--                   every exception including ones libraries throw and swallow
--                   -- turn it on to find one something upstream is catching.
--      <leader>re   NOT under the debugger: turn the last traceback in the run
--                   split into a quickfix list and jump to the innermost frame.
--                   :cnext walks outwards to the caller.
--
--    Inspecting:
--      K            hover docs normally; the VALUE under the cursor while the
--                   session is stopped. At a breakpoint that is the question
--                   you actually have, and it is the key your hands already
--                   reach for -- the docs are back the moment the session ends.
--      <leader>de   evaluate -- the word under the cursor in normal mode, or
--                   the SELECTION in visual mode, so you can highlight
--                   `self.cache[key]` and ask for exactly that
--      <leader>dr   toggle the repl -- a real python prompt inside the stopped
--                   frame, where every local is already in scope
--      <leader>du   toggle the dap-ui panes -- scopes / breakpoints / stacks /
--                   watches, a left sidebar only. No bottom drawer: its console
--                   element stays empty (everything runs in an integrated
--                   terminal) and the repl is <leader>dr on demand.
--
--    Watches, without leaving the code. When the expression is already on
--    screen the trip to the pane IS the cost of the watch, so these add one and
--    leave the cursor exactly where it was:
--      <leader>da   watch the expression under the cursor -- the whole dotted
--                   name (`self.cache`, not just `cache`) -- or the SELECTION
--                   in visual mode for what that cannot reach: `rows[i]['px']`,
--                   a slice, a call. Six watches is six keypresses, not six
--                   round trips. Works before a session starts, too: dap-ui
--                   keeps watches across sessions, so line them all up and
--                   then hit <F5>.
--      <leader>dA   prompt for an expression that is nowhere in the file, e.g.
--                   `len(self.pending)` or `[r.id for r in rows]`
--      <leader>dX   clear every watch -- they outlive the session that made
--                   them, which is the point, and also why the pane silts up
--                   with expressions from three bugs ago
--      <leader>dW   the other way round: into the pane, in insert, to TYPE one
--
--    Moving around a stopped session. The cost worth removing is the window
--    round-trip -- <C-w>h, read, <C-w>p is three keystrokes wrapped around the
--    one that did the work, paid every time you get curious:
--      <Esc>        (in any dap-ui pane, or the repl) back to the code. It
--                   FINDS the source window rather than using wincmd p, which
--                   is wrong the moment you have hopped between two panes.
--      <leader>ds   scopes  -- in AND out on the same key
--      <leader>dS   stacks  -- ditto
--      <leader>dw   watches -- ditto
--      <leader>df   jump the cursor to the line the program is stopped on, from
--                   wherever reading the code took you. The counterpart to
--                   dK/dJ: those choose which frame you are looking at, this
--                   puts you on the line about to execute in it.
--      <leader>dL   every breakpoint into the quickfix list, so :cnext walks
--                   them -- the breakpoints PANE shows the same set but cannot
--                   jump you to one
--
--    Inline values (dap-virtual-text). Each variable's value is printed past
--    the end of the line that produced it as you step -- usually enough that
--    you never open the scopes pane. Two things are tuned for space:
--      * position is `eol`, not the plugin's `inline` default. Inline INSERTS
--        the value into the line and pushes your code right, so a six-key dict
--        can shove the end of a statement off screen. At eol the values sit in
--        space that was empty anyway and the code never moves.
--      * values are cut to 40 CHARACTERS (not bytes -- a byte cut splits a
--        codepoint and leaves `<c3>` behind). A repr is however long the object
--        is; untruncated it stops being a hint and becomes the line.
--    The full value is always one key away, so the hint only has to be enough
--    to RECOGNISE a value, not to read it:
--      K            the value under the cursor, in a float
--      <leader>de   same, and works over a visual SELECTION
--      <leader>da   pin it in the watches pane and keep reading
--      <leader>dv   expand every value to full length; again to collapse
--      <leader>dV   virtual text off entirely, for a line long enough that
--                   even a truncated hint is in the way
--
--    Which venv runs your code: $VIRTUAL_ENV if one is active, else
--    $CONDA_PREFIX, else the first venv/.venv/env/.env directory in the cwd or
--    an LSP root. If none of those exist the session starts against mason's own
--    debugpy venv and dies on the first project import -- so activate the venv,
--    or keep a .venv in the project root. debugpy itself does NOT need to be
--    installed there; the adapter injects its own copy.
--
--    The run picker <F5> shows: `file` (this buffer), `file:args` (prompts for
--    argv), `file:libs` (same, but steps into library code), `module`
--    (python -m …), `attach`, `file:doctest`.
--
--  COPILOT  (zbirenbaum/copilot.lua) -- ghost text, never a cmp source
--      <M-y>        accept the suggestion
--      <M-w>        accept just the next WORD -- the rest is usually wrong
--      <M-]> <M-[>  cycle alternatives
--      <C-]>        dismiss
--      <leader>ct   suggestions off for this buffer, and on again
--
--    <Tab> is untouched and still cmp/LuaSnip. Copilot's own default accept is
--    <M-l>, which cannot work here: tmux takes M-l for select-pane with
--    `bind -n`, so nvim never sees it. Same for <M-Right>/<M-Down>.
--
--    Ghost text hides itself while the cmp menu is open, so the two never draw
--    over each other. It is Comment + italic: a suggestion should not look like
--    code you already wrote.
--
--    Excluded by FILETYPE only: gitcommit, gitrebase, dotenv, dap-repl. It runs
--    in every repo. :CopilotWhy names the rule when it is not live in a buffer;
--    :Copilot status only tells you that it is not.
--
--  WORKTREES
--    <leader>fw   pick a git worktree, cd into it, and land in find_files
--                 there. <Esc> out of the finder if the cd was the point.
--
--    Why it exists: claude puts agent worktrees at
--    <repo>/.claude/worktrees/<name> and excludes that path in
--    .git/info/exclude -- so <leader>ff CANNOT see into one from the main
--    checkout. fd honours the exclude, and the directory is hidden besides.
--    The exclusion is right: a worktree is a second full checkout, so without
--    it every file in the project would show up once per worktree in every
--    search. So the fix is not a flag on the finder -- it is to be in the
--    worktree. `git worktree list` is the same information on the command line.
--
--    No plugin: vim.ui.select routes through telescope-ui-select, so it is a
--    fuzzy picker for free -- the same trick the Makefile target pickers use.
--
--  GIT HUNKS  (lewis6991/gitsigns.nvim)
--
--  The inline half of "show me the diff": what changed on THIS line, answered
--  without leaving the line. What changed across a branch is a different
--  question and wants a different tool.
--
--  Prefix is <leader>g, not gitsigns' own <leader>h -- that is harpoon's menu
--  here, and harpoon is used far more often than any hunk operation.
--
--    The signs:
--      ┃            lines added or changed
--      ▁ / ▔        a deletion, below / above the cursor line
--      ~            a line changed AND lines deleted with it
--      ┆            (dashed) a file git has never seen -- untracked. Solid
--                   vs dashed is "new lines" vs "new file". Anything
--                   .gitignore covers stays dark: gitsigns looks untracked
--                   files up with `ls-files --others --exclude-standard`.
--
--    signcolumn is forced to `yes` in init.lua rather than left on `auto`, so
--    the column is always reserved. On `auto` the first hunk shifts the whole
--    file two columns right and undoing it shifts back -- text that jitters
--    sideways while you edit.
--
--    Moving:
--      ]c / [c      next / previous hunk. Inside a real diff split these fall
--                   through to vim's own diff-mode motions, which is what they
--                   have to mean there.
--
--    Reading:
--      <leader>gp   preview the hunk INLINE -- the old lines open underneath,
--                   in the buffer, no float to dismiss
--      <leader>gP   the same in a float, when the inline version would push too
--                   much of the file off screen
--      <leader>gb   full blame for this line: commit, author, date, message
--      <leader>gB   toggle the end-of-line blame virtual text (it is ON by
--                   default here) for when it is in the way
--      <leader>gd   diff this file against the INDEX (what `git diff` shows)
--      <leader>gD   diff this file against the last commit (`git diff HEAD`)
--      <leader>gq   every hunk in this buffer into the quickfix list
--      <leader>gQ   every hunk in the REPO into the quickfix list
--
--    Staging -- the point of the whole plugin. A buffer holding three unrelated
--    fixes becomes three commits without a single `git add -p`:
--      <leader>gs   stage the hunk under the cursor. On an ALREADY-staged hunk
--                   it unstages -- one key, both directions, which is why there
--                   is no separate unstage binding.
--      <leader>gr   discard the hunk (reset it to what git has)
--      <leader>gS   stage every change in the buffer
--      <leader>gR   discard every change in the buffer
--      {visual}gs   stage only the SELECTED lines -- part of a hunk, down to
--      {visual}gr   one line. Same for discard.
--
--    ih is a TEXT OBJECT, which is what makes this vim rather than a git client:
--      dih          delete the hunk under the cursor
--      vih          select it -- then <leader>gs to stage exactly that
--      =ih          reindent just it
--
--    diffopt+=linematch:60 is set in init.lua alongside this. It is neovim's own
--    diff refinement, off by default: without it a line with one word changed
--    shows as a whole line deleted plus a whole line added. Applies to every
--    diff nvim draws, these previews included.
--
--  REVIEWING A DIFF  (sindrets/diffview.nvim)
--
--  What gitsigns cannot answer, because the answer spans files: what changed
--  across the working tree, a commit, or a branch. File panel left, two-pane
--  diff right, in its own TAB.
--
--      <leader>gg   in and out on one key. Three states, the same shape as the
--                   dap-ui panes and tmux's <prefix>C: looking at it -> close,
--                   open in another tab -> go to it, neither -> open. The
--                   middle case matters because diffview opens in a new tab --
--                   without it a second press stacks a second review tab.
--      <leader>gm   review the whole branch against the default branch. The
--                   base is asked of the repo (origin/HEAD, else probing
--                   origin/main and origin/master) rather than assumed, and the
--                   range is `base...HEAD` -- THREE dots, so it diffs against
--                   the merge base and commits that landed on main after you
--                   branched are not counted as yours.
--      <leader>gh   this file's history: every commit that touched it, with the
--                   diff beside it rather than paged past. The good `git log -p`.
--      <leader>gH   the whole repo's history, same view
--      {visual}gh   the history of just the SELECTED LINES -- `git log -L`, the
--                   "who last touched this function" query that is unusable on
--                   the command line
--
--    Getting back out. Any of the four keys above closes the view when pressed
--    from inside it -- whichever one opened it -- so there is nothing to
--    remember about which are toggles. :DiffviewClose is the long way, and `gf`
--    on a row is the other way: it leaves the review and opens the real file at
--    that line. Diffview lives in its own tab, so gt/gT work too.
--
--    Inside the view (diffview's own, buffer-local):
--      <tab> / <s-tab>   next / previous file
--      -  or  s     stage / unstage the file under the cursor
--      S  /  U      stage all / unstage all
--      X            restore the file -- discard its changes
--      gf           leave the review and open the real file at that line
--      <leader>e    FOCUS THE FILE PANEL here, not neo-tree. Diffview's
--                   buffer-local map wins, which is the more useful meaning
--                   while reviewing.
--      g?           the full keymap
--
--    It uses neovim's OWN diff engine, so diffopt+=linematch:60 applies here
--    too, and enhanced_diff_hl is on: the changed REGION within a changed line
--    is highlighted, not just the whole line. On someone else's edit that is the
--    difference between "this line moved" and "this argument moved".
--
--  WINDOWS  (nvim's own splits)
--    M-h/j/k/l    move between nvim windows -- BUT only while tmux is in nvim
--                 mode. M-o (in tmux) flips which layer these steer: tmux
--                 panes by default, nvim's splits when flipped, with
--                 [NVIM WINDOWS] shown in the tmux bar while it is.
--                 Set in terminal mode too, so it works in the <leader>mm run
--                 split and the dap repl.
--    <C-w>hjkl    always nvim windows, untouched. These exist because
--                 <C-h/j/k/l> cannot be the window keys here -- three of the
--                 four are dap stepping commands.
--    M-Left/Down/Up/Right   always tmux panes, whatever the mode -- the escape
--                 hatch if you toggle and forget.
--
--  CORE  (no plugin)
--    jk           (insert mode) escape to normal mode — the one you added
--    <C-q>        BLOCKWISE visual. WezTerm takes <C-v> for paste, so it never
--                 reaches nvim; vim aliases <C-q> to <C-v>, so this is the very
--                 same command.
--    M-u / M-d    half page up / down, aliasing C-u/C-d so the same keys
--                 scroll nvim, tmux copy mode and claude
--
--  See tutorial.rs for a guided, hands-on tour of these plugins, and
--  drills.py for the speed course -- the same material as timed drills
--  with pass marks, rather than explanation.


-- ----------------------------------------------------------------------------
--  CHEAT SHEET — the 12 that matter most
-- ----------------------------------------------------------------------------
--    s{c}{c}     jump to any label on screen (flash) — the anti-hjkl key
--    f{c} ;      jump onto a char on the line, repeat
--    w  b  e     word forward / back / end
--    0  ^  $     line start / first word / end
--    /  n        search, next match           *   search word under cursor
--    gg  G       top / bottom of file         {count}G  absolute line
--    {  }        paragraph up / down
--    Ctrl-d/u    half page down / up   (M-d/M-u do the same, everywhere)
--    H  M  L     screen top / middle / bottom
--    zz          recenter the screen
--    `` Ctrl-o   back to previous spot / jump history
--    ci(  ciw    change inside parens / word (operator + motion)
--    %           matching bracket
--
--  Practice loop: pick a visible target, ask "what's the ONE motion that gets
--  me there?", use it. When you catch yourself holding `j`, stop and count.
-- ----------------------------------------------------------------------------

return { sample = sample, waypoint = waypoint, reuse = reuse_the_waypoint, edit_me = edit_me }
