-- ============================================================================
--  motions.lua — get around as fast as possible
-- ============================================================================
--
--  Open in nvim:   nvim nvim/motions.lua
--
--  This is a hands-on drill file for MOVING, not editing. Every section has a
--  `TRY IT` with a real target in this buffer. Do them in normal mode (press
--  `jk` or <Esc> first). Stay off the arrow keys — the whole point is to reach
--  for these instead.
--
--  The golden rule: NEVER press `hjkl` more than a couple times in a row. If a
--  target is far, there's a faster motion below to get there in one jump.
--
--  TIP: counted jumps like `5j` are aimed by READING the gutter, never by
--  counting rows. init.lua sets hybrid line numbers (number + relativenumber),
--  so the cursor line shows its absolute number and every other line shows how
--  far away it is — the number you type. `:Drill counts` drills exactly this.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  1. WITHIN A LINE  — stop walking with `l`
-- ----------------------------------------------------------------------------
--    w / W   forward to start of next word  (W = ignore punctuation)
--    b / B   back to start of previous word
--    e / ge  end of word (forward / backward)
--    0       first column      ^   first non-blank      $   end of line
--    f{c}    jump forward ONTO the next {c} on this line
--    t{c}    jump forward UP TO (just before) the next {c}
--    F / T   same, backwards            ;  repeat last f/t      ,  reverse it
--    %       jump to the matching ) ] }
--
--  TRY IT on the line below (put cursor at its start with `0`):
--    * press `w` a few times to hop word-to-word
--    * press `$` to shoot to the end, `^` to come back to the first word
--    * press `f(` to land on the paren, then `%` to bounce to its match
--    * press `t,` to stop right before the comma, then `;` for the next one
local sample = "choose(alpha, beta, gamma, delta)"   -- targets: ( ) , , words


-- ----------------------------------------------------------------------------
--  2. FIND-CHAR IS YOUR FASTEST HORIZONTAL MOVE
-- ----------------------------------------------------------------------------
--  `f` / `t` beat mashing `w`. Think "I want to be AT the x" -> `fx`.
--  Overshot? `,` steps back. Wrong char? just `f{other}`.
--
--  TRY IT: from column 0 of the line below, reach the word "needle" in ONE
--  press with `fn` (then `;` if it lands on the wrong n). Then `$` and `Fh`
--  to fly back to the "h" in "haystack".
--    haystack haystack haystack needle haystack haystack


-- ----------------------------------------------------------------------------
--  3. UP AND DOWN THE FILE
-- ----------------------------------------------------------------------------
--    gg      top of file            G       bottom of file
--    {count}G / :{count}   go to an absolute line number  (e.g. 120G)
--    {count}j / {count}k   jump N lines (5j = down 5) — pair with relativenumber
--    {  }    previous / next blank-line paragraph  (great for code blocks)
--    Ctrl-d  half page down         Ctrl-u  half page up   (keeps context)
--    Ctrl-f  full page forward      Ctrl-b  full page back
--    H M L   jump to the top / middle / bottom of the VISIBLE screen
--    zz zt zb  scroll current line to center / top / bottom (reframe, don't move)
--
--  TRY IT:
--    * press `G` to hit the bottom of the file, then `gg` to snap back here
--    * press `}` a few times to skip paragraph-by-paragraph through this file
--    * press `L` to drop to the bottom of the screen, `H` for the top, `M` mid
--    * press `Ctrl-d`, then `zz` to recenter what you land on


-- ----------------------------------------------------------------------------
--  4. SEARCH — teleport to anything by name
-- ----------------------------------------------------------------------------
--    /text<CR>   search forward       ?text<CR>   search backward
--    n / N       next / previous match (N = opposite direction)
--    *  / #      search for the WORD under the cursor, forward / back
--    (with hlsearch, `:noh` clears the highlight when you're done)
--
--  Searching is usually the FASTEST way to cross a file — if you can see it or
--  name it, `/` gets you there without counting a single line.
--
--  TRY IT: put the cursor on the word `waypoint` below and press `*` — you'll
--  jump straight to its next occurrence; keep pressing `n` to cycle them.
local waypoint = 1
-- ... some distance later ...
local reuse_the_waypoint = waypoint + waypoint   -- * from above lands here


-- ----------------------------------------------------------------------------
--  5. MARKS & THE JUMP LIST — leave, then come back
-- ----------------------------------------------------------------------------
--    m{a-z}   drop a named mark here      `{a-z}   jump back to that mark
--    ``       jump back to where you were BEFORE the last big jump
--    Ctrl-o   go back through your jump history (older positions)
--    Ctrl-i   go forward again (Tab)      :jumps   see the whole list
--    gd / gr  (this config, LSP) jump to a symbol's definition / references
--    ]d / [d  (this config, LSP) jump to the next / previous diagnostic
--    K        (this config, LSP) peek hover docs without leaving your spot
--
--  This is how you bounce between two spots without pinning them in harpoon.
--
--  TRY IT: press `ma` here to set mark 'a'. Now `G` to the bottom, poke
--  around, then press `` `a `` to teleport back to this exact line. Try `Ctrl-o`
--  / `Ctrl-i` to walk your jump history.


-- ----------------------------------------------------------------------------
--  6. MOTIONS + OPERATORS = editing at the same speed
-- ----------------------------------------------------------------------------
--  Every motion above doubles as a target for an operator. Same keys, now they
--  DO something over the distance they'd move:
--    d{motion}  delete   c{motion}  change   y{motion}  yank
--    dw  d$  d^        ci(  "change inside ()"      di"  yi{
--    daw "delete a word"    dt,  "delete up to the comma"    d/foo  to a search
--    ciw is the workhorse: change the whole word the cursor is on, anywhere in it
--
--  TRY IT: put the cursor anywhere inside the parens below and press `ci(` —
--  the args vanish and you're in insert mode ready to retype. Or `diw` on a
--  word to nuke just that word.
local edit_me = "build(one, two, three)"


-- ----------------------------------------------------------------------------
--  7. PROJECT-WIDE — when the target isn't in this file (this config)
-- ----------------------------------------------------------------------------
--  Once you're fast within a file, jumping BETWEEN files is the next win.
--  Rule of thumb: within a file use `/` and `f`; across files use telescope;
--  for the 2-4 files you live in, pin them with harpoon.
--
--  TELESCOPE  (nvim-telescope/telescope.nvim, powered by plenary.nvim)
--    <leader>ff   find files by name
--    <leader>fg   live grep — search file *contents* across the project
--    <leader>fb   jump between open buffers
--    <leader>fh   search neovim's :help docs
--    <leader>fe   file browser, opened at the current file's directory
--                 (telescope-file-browser.nvim; also creates/renames/deletes)
--
--    telescope-ui-select.nvim also routes vim.ui.select() here, so every menu
--    nvim raises is a telescope dropdown you can fuzzy-filter rather than a
--    numbered list you read: <leader>ca code actions, <leader>mm / <leader>dM
--    make targets. Type to narrow, <CR> to pick, <Esc> to back out.
--
--  NEO-TREE  (nvim-neo-tree/neo-tree.nvim) — the sidebar tree, for browsing
--  structure rather than jumping to a file you can already name.
--    <leader>e    toggle the sidebar, revealing the current file in the tree
--    <space>      expand / collapse the directory under the cursor, in place
--    <CR>         open — a file in the last window, a directory expands it
--    C  /  z      collapse this node / collapse every node
--    <bs>         move the tree root up one directory
--    .            make the directory under the cursor the new root
--    s  /  S  /  t  open in a vsplit / split / new tab
--    P            floating preview without leaving the tree (<C-f>/<C-b> scroll)
--    a  A  d  r   add file / add directory / delete / rename
--    y  x  p      copy / cut / paste under the cursor
--    H            toggle hidden + gitignored files
--    /  f         fuzzy-find within the tree / filter and keep the filter
--    [g  ]g       previous / next git-modified file
--    <  >         switch source: filesystem / buffers / git status
--    ?            full keymap help, inside the tree
--
--  HARPOON  (ThePrimeagen/harpoon, branch harpoon2)
--    <leader>a    pin the current file to the list
--    <leader>h    toggle the quick menu (reorder / remove pins)
--    <leader>1    teleport to pinned file 1
--    <leader>2    teleport to pinned file 2
--    <leader>3    teleport to pinned file 3
--    <leader>4    teleport to pinned file 4


-- ----------------------------------------------------------------------------
--  8. THE REST OF YOUR KEYMAPS — every custom binding in init.lua
-- ----------------------------------------------------------------------------
--  Not strictly "motions", but this is the full set so nothing's a surprise.
--
--  LSP  (neovim/nvim-lspconfig; servers installed by mason.nvim +
--        mason-lspconfig.nvim — lua_ls is auto-installed)
--    gd           go to definition        (opens a telescope picker)
--    gr           find references         (opens a telescope picker)
--    K            hover docs
--    ]d / [d      next / previous diagnostic
--    <leader>rn   rename the symbol everywhere
--    <leader>ca   code actions (quick fixes)
--
--  COMPLETION  (hrsh7th/nvim-cmp + sources cmp-nvim-lsp, cmp-buffer, cmp-path;
--               snippets via L3MON4D3/LuaSnip + saadparwaiz1/cmp_luasnip)
--    <C-Space>    force the completion menu open
--    <Tab> / <S-Tab>   next / prev item (and hop between snippet fields)
--    <CR>         confirm the highlighted item
--    <C-f> / <C-b>     scroll the docs popup down / up
--
--  DEBUGGER  (mfussenegger/nvim-dap + rcarriga/nvim-dap-ui; the debugpy
--             adapter is installed by jay-babu/mason-nvim-dap.nvim, and the
--             python configurations come from mfussenegger/nvim-dap-python)
--
--  Same protocol and same adapter VS Code uses, so behaviour is identical --
--  what dap-ui adds is the windows. Two ways in:
--    <F5>         pick a configuration. In a project with .vscode/launch.json,
--                 that file's configurations are in the list automatically --
--                 nvim-dap reads it on demand, so VS Code's Run-and-Debug
--                 dropdown and this picker are literally the same list.
--    <leader>dM   pick a Makefile target instead (see Running, below).
--  Either way, put the cursor on a line and <leader>db first.
--
--  launch.json caveat: nvim's JSON parser is stricter than VS Code's. Trailing
--  commas, and `//` comments sharing a line with code, make the whole file
--  unparseable and nvim-dap silently falls back to the generic configs. Put
--  comments on their own line and drop the trailing commas.
--
--    F-keys, exactly VS Code's:
--      <F5>       start a session / resume from a stop
--      <F10>      step over          <F11>   step into
--      <S-F11>    step out           <F12>   step out (fallback binding)
--
--    Breakpoints:
--      <leader>db   toggle a breakpoint on this line
--      <leader>dB   conditional -- prompts for a python expression (`i == 4721`)
--      <leader>dp   logpoint -- prints to the repl and never stops; `{}`
--                   interpolates, so `row {i} = {row}`. A print statement that
--                   isn't in the file and can't be committed by accident.
--      <leader>dx   clear every breakpoint
--
--    Running:
--      <leader>mm   pick a Makefile target and just RUN it in a terminal split
--                   -- no debugger, no attach. The everyday case; <leader>dM is
--                   the same picker when you want to stop inside it.
--      <leader>dM   pick a Makefile target, run it with DEBUG=1 in a terminal
--                   split, and attach automatically -- the whole IDE "Run"
--                   button, but parameterised by the Makefile rather than by a
--                   second copy of the arguments. Prompts for extra make vars
--                   (`BOOTSTRAPS=5 CONFIDENCE=0.8`). Set breakpoints FIRST:
--                   --wait-for-client releases the moment nvim attaches.
--      <leader>dc   continue (same as <F5>)
--      <leader>dC   run to the cursor -- one-shot breakpoint here, then resume
--      <leader>dl   re-run the last configuration, skipping the picker
--      <leader>dm   debug the test method the cursor is inside (pytest/unittest)
--      <leader>dt   terminate the session -- a HARD kill of the process, not a
--                   Ctrl-C, so no KeyboardInterrupt and no `finally` blocks. To
--                   let a run wind down cleanly, Ctrl-C its terminal split
--                   instead; to stop debugging but let it finish, use
--                   :lua require('dap').disconnect({terminateDebuggee = false})
--      <leader>dq   tidy up: terminate if still running, then close the panes,
--                   the repl, and the <leader>dM terminal split. The dap-ui
--                   panes close on their own when a session ends -- this is for
--                   the terminal split, which is kept on purpose so the run's
--                   output outlives the session. Also as :DebugCleanup, and it
--                   reports how many splits it closed rather than failing quiet.
--
--    Inspecting:
--      <leader>du   toggle the dap-ui panes (scopes / breakpoints / stacks /
--                   watches on the left, repl in the drawer below)
--      <leader>de   evaluate -- the word under the cursor in normal mode, or
--                   the SELECTION in visual mode, so you can highlight
--                   `self.cache[key]` and ask for exactly that
--      <leader>dr   toggle the repl -- a real python prompt inside the stopped
--                   frame, where every local is already in scope
--
--    Values also appear inline at end-of-line as you step (dap-virtual-text),
--    which is usually enough that you never open the scopes pane.
--
--    Which venv runs your code: $VIRTUAL_ENV if one is active, else
--    $CONDA_PREFIX, else the first venv/.venv/env/.env directory in the cwd or
--    an LSP root. If none of those exist the session starts against mason's own
--    debugpy venv and dies on the first project import -- so activate the venv,
--    or keep a .venv in the project root. debugpy itself does NOT need to be
--    installed there; the adapter injects its own copy.
--
--    The run picker <F5> shows: `file` (this buffer), `file:args` (prompts for
--    argv), `file:libs` (same, but steps into library code), `module`
--    (python -m …), `attach`, `file:doctest`.
--
--  CORE  (no plugin)
--    jk           (insert mode) escape to normal mode — the one you added
--
--  See tutorial.lua for a guided, hands-on tour of these plugins.


-- ----------------------------------------------------------------------------
--  CHEAT SHEET — the 12 that matter most
-- ----------------------------------------------------------------------------
--    f{c} ;      jump onto a char on the line, repeat
--    w  b  e     word forward / back / end
--    0  ^  $     line start / first word / end
--    /  n        search, next match           *   search word under cursor
--    gg  G       top / bottom of file         {count}G  absolute line
--    {  }        paragraph up / down
--    Ctrl-d/u    half page down / up
--    H  M  L     screen top / middle / bottom
--    zz          recenter the screen
--    `` Ctrl-o   back to previous spot / jump history
--    ci(  ciw    change inside parens / word (operator + motion)
--    %           matching bracket
--
--  Practice loop: pick a visible target, ask "what's the ONE motion that gets
--  me there?", use it. When you catch yourself holding `j`, stop and count.
-- ----------------------------------------------------------------------------

return { sample = sample, waypoint = waypoint, reuse = reuse_the_waypoint, edit_me = edit_me }
